### ISSUE TITLE
Invalid userId

### ISSUE THREAD

**Issue by urbanovich** [paypal/buttonmanager-sdk-php#13]
Good afternoon!!!
I write about the button manager-sdk-php, you could throw a working example for the use of this library since used the example of README.dm file:

```
$config = array(
    'mode' => 'sandbox',
    'acct1.UserName' => 'jb-us-seller_api1.paypal.com',
    'acct1.Password' => 'WX4WTU3S8MY44S7F',
);

$buttonSearchReq = new \PayPal\PayPalAPI\BMButtonSearchReq();
$buttonSearchReq->BMButtonSearchRequest = new \PayPal\PayPalAPI\BMButtonSearchRequestType();

$paypalService = new \PayPal\Service\PayPalAPIInterfaceServiceService($config);
$buttonSearchResponse = $paypalService->BMButtonSearch($buttonSearchReq);

if(strtoupper($buttonSearchResponse->Ack) == 'SUCCESS') {
    // Success
    \Helpers\Log::write($buttonSearchResponse);
}

$paypalService = new \PayPal\Service\PayPalAPIInterfaceServiceService($config);

// Use the default account (the first account) configured in sdk_config.ini
$response = $paypalService->BMButtonSearch($buttonSearchReq);

// Use a specific account configured in sdk_config.ini
$response = $paypalService->BMButtonSearch($buttonSearchReq, 'jb-us-seller_api1.paypal.com');

// Pass in a dynamically created API credential object
$cred = new \PayPal\Auth\PPCertificateCredential("username", "password", "path-to-pem-file");
$cred->setThirdPartyAuthorization(new \PayPal\Auth\PPTokenAuthorization("accessToken", "tokenSecret"));
$response = $paypalService->BMButtonSearch($buttonSearchReq, $cred);
```
and I see an exception:
```
Notice: Undefined variable: userName in /var/www/presta_multi_1.6.loc/modules/belvg_ppsubscriptions/vendor/paypal/sdk-core-php/lib/PayPal/Core/PPCredentialManager.php on line 110

Notice: Undefined variable: userName in /var/www/presta_multi_1.6.loc/modules/belvg_ppsubscriptions/vendor/paypal/sdk-core-php/lib/PayPal/Core/PPCredentialManager.php on line 114

Notice: Undefined variable: userName in /var/www/presta_multi_1.6.loc/modules/belvg_ppsubscriptions/vendor/paypal/sdk-core-php/lib/PayPal/Core/PPCredentialManager.php on line 119

Notice: Undefined index: in /var/www/presta_multi_1.6.loc/modules/belvg_ppsubscriptions/vendor/paypal/sdk-core-php/lib/PayPal/Core/PPCredentialManager.php on line 138

Fatal error: Uncaught exception 'PayPal\Exception\PPInvalidCredentialException' with message 'Invalid userId ' in /var/www/presta_multi_1.6.loc/modules/belvg_ppsubscriptions/vendor/paypal/sdk-core-php/lib/PayPal/Core/PPCredentialManager.php:144 Stack trace: #0 /var/www/presta_multi_1.6.loc/modules/belvg_ppsubscriptions/vendor/paypal/sdk-core-php/lib/PayPal/Handler/PPMerchantServiceHandler.php(34): PayPal\Core\PPCredentialManager->getCredentialObject(NULL) #1 /var/www/presta_multi_1.6.loc/modules/belvg_ppsubscriptions/vendor/paypal/sdk-core-php/lib/PayPal/Core/PPAPIService.php(83): PayPal\Handler\PPMerchantServiceHandler->handle(Object(PayPal\Core\PPHttpConfig), Object(PayPal\Core\PPRequest), Array) #2 /var/www/presta_multi_1.6.loc/modules/belvg_ppsubscriptions/vendor/paypal/sdk-core-php/lib/PayPal/Core/PPAPIService.php(63): PayPal\Core\PPAPIService->runHandlers(Object(PayPal\Core\PPHttpConfig), Object(PayPal\Core\PPRequest)) #3 /var/www/presta_multi_1.6.loc/modules/belvg_ppsubscriptions/vendor/paypal/sdk-core-php/lib/PayP in /var/www/presta_multi_1.6.loc/modules/belvg_ppsubscriptions/vendor/paypal/sdk-core-php/lib/PayPal/Core/PPCredentialManager.php on line 144
```
it is probably due to not complete $config
I will be grateful for a comment.

**Comment by suletm** [comment]
Although I had slightly different error message I think this might help. Try to add Signature field into your config like this:

$config = array(
'mode' => 'sandbox',
'acct1.UserName' => 'jb-us-seller_api1.paypal.com',
'acct1.Password' => 'WX4WTU3S8MY44S7F',
'acct1.Signature' => 'XXXXXX'
);

Replace XXXXXX with your signature.

P.S. hope you did not paste your real account credentials.

**Comment by jaypatel512** [comment]
Hey @urbanovich !

Adding a `Signature` should fix the error your are seeing. I will go ahead and update the sample in README.md. 

Thanks @suletm !
